import{db}from'./config.js';import{loadProfile,loadWorkouts,loadLatestPrescription,loadMeasurements}from'./data.js';import{esc,toast,initials}from'./ui.js';import{assessmentView}from'./assessment.js';import{workoutDetail}from'./workouts.js';
let state={session:null,profile:null,workouts:[],prescription:null,measurements:[],tab:'home'};
const app=document.querySelector('#app');
function authView(){app.innerHTML=`<div class="auth"><div class="authCard"><div class="logo">FP</div><h1>FITPRO V7</h1><p class="muted">Treino personalizado com acompanhamento inteligente.</p><form id="auth" class="form"><input id="name" placeholder="Nome completo (só no cadastro)"><input id="email" type="email" placeholder="E-mail" required><input id="pass" type="password" minlength="6" placeholder="Senha" required><div class="actions"><button class="btn primary" data-mode="login">Entrar</button><button class="btn ghost" data-mode="signup">Criar conta</button></div></form></div></div>`;document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=async e=>{e.preventDefault();const mode=b.dataset.mode,email=document.querySelector('#email').value,password=document.querySelector('#pass').value,name=document.querySelector('#name').value.trim();if(mode==='login'){const{error}=await db.auth.signInWithPassword({email,password});if(error)toast(error.message,true)}else{const{data,error}=await db.auth.signUp({email,password,options:{data:{full_name:name}}});if(error)return toast(error.message,true);if(data.user){await db.from('fitpro_profiles').upsert({id:data.user.id,full_name:name||email.split('@')[0],role:'student'});toast('Conta criada!')}}})}
async function refresh(){state.profile=await loadProfile(state.session.user.id);state.workouts=await loadWorkouts(state.session.user.id);state.prescription=await loadLatestPrescription(state.session.user.id);state.measurements=await loadMeasurements(state.session.user.id)}
function shell(content){const p=state.profile;app.innerHTML=`<div class="shell"><header class="top"><div class="brand"><div class="logo">FP</div><div><b>FITPRO</b><small class="muted">V7</small></div></div><div class="avatar">${initials(p.full_name)}</div></header><main>${content}</main><nav class="nav"><button data-tab="home" class="${state.tab==='home'?'active':''}">⌂<br>Início</button><button data-tab="treinos" class="${state.tab==='treinos'?'active':''}">🏋️<br>Treinos</button><button data-tab="progresso" class="${state.tab==='progresso'?'active':''}">📈<br>Progresso</button><button data-tab="perfil" class="${state.tab==='perfil'?'active':''}">👤<br>Perfil</button></nav></div>`;document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{state.tab=b.dataset.tab;render()})}
function home(){const next=state.workouts.find(w=>!w.completed_at),done=state.workouts.filter(w=>w.completed_at).length;return `<div class="hero"><span class="eyebrow">Treino de hoje</span><h1>${next?esc(next.title):'Seu plano personalizado'}</h1><p class="muted">${next?esc(next.focus||'Plano inteligente'):'Complete sua avaliação para a IA montar seu programa.'}</p><div class="actions">${next?`<button class="btn primary" id="start">Iniciar treino</button>`:`<button class="btn primary" id="assessment">Fazer avaliação</button>`}</div></div><div class="grid section"><div class="card stat"><span class="muted">Treinos feitos</span><strong>${done}</strong></div><div class="card stat"><span class="muted">Plano</span><strong>${state.prescription?.status==='ready'?'Ativo':'Pendente'}</strong></div></div>${state.prescription?`<div class="section"><h2>Seu plano</h2><div class="card"><span class="tag">IA</span><p>${esc(state.prescription.summary||'')}</p></div></div>`:''}`}
function workouts(){return `<h1>Meus treinos</h1>${state.workouts.length?state.workouts.map(w=>`<div class="workout"><span class="tag">${w.scheduled_for||''}</span><h3>${esc(w.title)}</h3><p class="muted">${esc(w.focus||'')} • ${w.estimated_minutes||60} min</p><div class="actions"><button class="btn ghost" data-workout="${w.id}">Abrir</button></div></div>`).join(''):`<div class="card"><p class="muted">Nenhum treino publicado ainda.</p><button id="assessment" class="btn primary">Fazer avaliação</button></div>`}
function progress(){const m=state.measurements[0];return `<h1>Progresso</h1><div class="grid"><div class="card stat"><span class="muted">Peso</span><strong>${m?.weight_kg?m.weight_kg+' kg':'—'}</strong></div><div class="card stat"><span class="muted">Treinos</span><strong>${state.workouts.filter(w=>w.completed_at).length}</strong></div></div><div class="section"><div class="card"><p class="muted">A V7 registra séries, cargas e repetições. Gráficos e recordes pessoais entram na próxima camada após estabilizarmos o fluxo principal.</p></div></div>`}
function profile(){return `<h1>Perfil</h1><div class="card"><h2>${esc(state.profile.full_name)}</h2><p class="muted">${state.profile.role==='coach'?'Personal':'Aluno'}</p></div><div class="actions"><button id="assessment" class="btn ghost">Refazer avaliação</button><button id="logout" class="btn danger">Sair</button></div>`}
function bind(){document.querySelector('#assessment')?.addEventListener('click',()=>assessmentView(state,async()=>{await refresh();state.tab='home';render()}));document.querySelector('#start')?.addEventListener('click',()=>{const next=state.workouts.find(w=>!w.completed_at);if(next)workoutDetail(next,render)});document.querySelectorAll('[data-workout]').forEach(b=>b.onclick=()=>workoutDetail(state.workouts.find(w=>String(w.id)===b.dataset.workout),render));document.querySelector('#logout')?.addEventListener('click',async()=>{await db.auth.signOut();state={session:null,profile:null,workouts:[],prescription:null,measurements:[],tab:'home'};authView()})}
function render(){if(!state.session)return authView();shell(state.tab==='home'?home():state.tab==='treinos'?workouts():state.tab==='progresso'?progress():profile());bind()}
async function boot(session){state.session=session;if(!session)return render();try{await refresh();render()}catch(e){toast(e.message||String(e),true)}}
db.auth.onAuthStateChange((_e,s)=>boot(s));db.auth.getSession().then(({data})=>boot(data.session));if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});
